{% set versions = {
    "4.1.0": "40f9394fd9db97005dd18da11a5e3930c1b351b14ab83b19d79f83d11a40d8d2",
    "4.0.2": "7a3bed88d95bea5ae2cc6b79808b4c91cd11ec840e3308de5cb34685a1470363", # require patching
    "3.1.11": "89f359564c124dbccbab7a4ac7c8fa5edcee70e401e2a3c2eff482f9dbaa4a9f"
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "rivet")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  url: "https://rivet.hepforge.org/downloads/?f=Rivet-{{ version }}.tar.gz"
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}
#  patches: # patch might be required for 4.0.2
#    - patches/cstdint.patch

requirements:
  build:
    - python
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}

    - make

  host:
    - zlib
    - yoda
    - fastjet
    - fastjet-contrib
    - hepmc

  run:
    - zlib
    - yoda
    - fastjet
    - fastjet-contrib
    - hepmc

about:
  home: "https://rivet.hepforge.org"
  license: "GPL-3.0"
  summary: "Rivet - the particle-physics MC analysis toolkit"
  description: |
    The Rivet toolkit (Robust Independent Validation of Experiment and Theory) is a system for
    validation of Monte Carlo event generators. It provides a large (and ever growing) set of
    experimental analyses useful for MC generator development, validation, and tuning, as well as a
    convenient infrastructure for adding your own analyses.

extra:
  recipe-maintainers:
    - meiyasan
